ports/dguitar: Clean up.
git-svn-id: file:///tmp/crux.sepen.svnrepo/trunk/ports@460 e5078a59-c42a-0410-a761-6d5b026a78ea

diff --git a/dguitar/Pkgfile b/dguitar/Pkgfile
--- a/dguitar/Pkgfile
+++ b/dguitar/Pkgfile
@@ -1,23 +1,44 @@
-# Description:  DGuitar is a Guitar Pro (*.gp4,*.gp3, *.gtp) viewer and player
-# URL:          http://dguitardl.sourceforge.net/
-# Maintainer:   Jose V Beneyto, sepen at users dot sourceforge dot net
-# Packager:     Jose V Beneyto, sepen at users dot sourceforge dot net
-# Depends on:   x11,jdk
+# Description: DGuitar is a Guitar Pro (*.gp4,*.gp3, *.gtp) viewer and player
+# URL: http://dguitar.sourceforge.net/
+# Maintainer: Jose V Beneyto, sepen at users dot sourceforge dot net
+# Packager: Jose V Beneyto, sepen at users dot sourceforge dot net
+# Depends on: xorg-libx11,jdk
 
 name=dguitar
 version=0.5.8
-release=2
-source=(http://dl.sourceforge.net/sourceforge/$name/DGuitar-$version.zip \
-	dguitar.sh)
+release=3
+source=(http://dl.sourceforge.net/sourceforge/${name}/DGuitar-${version}.zip)
 
 build() {
-	mkdir -p $PKG/usr/{bin,share/$name}
-	mkdir -p $PKG/usr/share/$name/{lang,files,skins}
-	install -m 755 dguitar.sh $PKG/usr/bin/$name
-	install -m 644 DGuitar-$version/dist/*.jar $PKG/usr/share/$name/
-	install -m 644 DGuitar-$version/lang/lang.properties $PKG/usr/share/$name/lang/
-	mkdir -p $PKG/usr/share/$name/skins/{default,compact}
-	install -m 644 DGuitar-$version/skins/{*.gif,*.png} $PKG/usr/share/$name/skins/
-	install -m 644 DGuitar-$version/skins/default/* $PKG/usr/share/$name/skins/default
-	install -m 644 DGuitar-$version/skins/compact/* $PKG/usr/share/$name/skins/compact
+  install -d ${PKG}/usr/share/${name}
+	install -m 644 DGuitar-${version}/dist/*.jar ${PKG}/usr/share/${name}
+	install -D -m 0644 DGuitar-${version}/lang/lang.properties \
+    ${PKG}/usr/share/${name}/lang/lang.properties
+  mv DGuitar-${version}/skins $PKG/usr/share/${name}
+  rm -f `find ${PKG}/usr/share/${name} -type f -name 'Thumbs.db'` \
+        `find ${PKG}/usr/share/${name} -type f -name 'readme.txt'`
+  install -d ${PKG}/usr/bin
+  cat > ${PKG}/usr/bin/${name} <<EOF
+#!/bin/sh
+
+JAVA_BIN_PATH=/usr/lib/java/bin
+
+if [ ! -d \$JAVA_BIN_PATH ] 
+then 
+	echo "error: can't find \$JAVA_BIN_PATH"
+	exit 1
+fi
+
+export PATH=\$PATH:\$JAVA_BIN_PATH
+
+cd /usr/share/${name}
+#./DGuitar.sh
+java -Dapple.laf.useScreenMenuBar=true \
+     -Dcom.apple.mrj.application.apple.menu.about.name=DGuitar \
+     -jar DGuitar.jar
+cd -
+
+# End of file
+EOF
+  chmod +x ${PKG}/usr/bin/${name}
 }
